# Generated by Django 2.1.15 on 2020-05-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [        
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ]
        ),         
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('property_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('title', models.CharField(default='', max_length=255)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=35)),
            ]
        ),        
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=35)),
            ]
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('activity_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('create_at', models.DateTimeField()),                
            ]
        )    
    ]
