# Generated by Django 2.1.15 on 2020-05-08 02:21
from django.conf import settings
from django.db import migrations, models
import django.db.models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [    
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('schedule', models.DateTimeField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField()),
                ('status', models.CharField(max_length=35)),
            ],
        ),     
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.ForeignKey(to='activitys.Property', null=True, on_delete=models.CASCADE)),
                ('schedule', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('status', models.CharField(max_length=35)),
            ]
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(to='activitys.Activity', null=True, on_delete=models.CASCADE)),
                ('answers', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
            ]
        )
    ]
